"""
Standalone Strands Agent: returns_refunds_agent
Generated by AgentCore MCP Server

Integrations:
- Memory: Disabled
- Gateway: Disabled
- Knowledge Base: Enabled
"""

import os
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)

# ============================================================================
# KNOWLEDGE BASE CONFIGURATION
# ============================================================================

kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")
print(f"✓ Knowledge Base ID: {kb_id}")

# System prompt
system_prompt = f"""You are a helpful returns and refunds assistant. Help customers check return eligibility, calculate refunds, and understand policies. Use the retrieve tool to access Amazon return policy documents for accurate information. Be friendly and accurate.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query"""

# Custom tool definitions
@tool
def check_return_eligibility(purchase_date: str, category: str) -> dict:
    """Check if an item is eligible for return.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (e.g., 'electronics', 'clothing', 'books')
    
    Returns:
        dict with 'eligible' (bool) and 'reason' (str)
    """
    
    try:
        purchase = datetime.strptime(purchase_date, '%Y-%m-%d')
        today = datetime.now()
        days_since_purchase = (today - purchase).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 30,
            'books': 30,
            'jewelry': 30,
            'home': 30,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase <= window:
            return {
                'eligible': True,
                'reason': f'Item is within {window}-day return window ({days_since_purchase} days since purchase)'
            }
        else:
            return {
                'eligible': False,
                'reason': f'Item is outside {window}-day return window ({days_since_purchase} days since purchase)'
            }
    except ValueError:
        return {
            'eligible': False,
            'reason': 'Invalid date format. Please use YYYY-MM-DD format.'
        }

@tool
def calculate_refund_amount(original_price: float, condition: str, return_reason: str) -> dict:
    """Calculate the refund amount for a returned item.
    
    Args:
        original_price: Original purchase price
        condition: Item condition ('new', 'opened', 'used', 'damaged')
        return_reason: Reason for return ('defective', 'wrong_item', 'changed_mind', 'other')
    
    Returns:
        dict with 'refund_amount' (float), 'refund_percentage' (int), and 'explanation' (str)
    """
    condition = condition.lower()
    return_reason = return_reason.lower()
    
    # Base refund percentage by condition
    condition_multipliers = {
        'new': 1.0,
        'opened': 0.9,
        'used': 0.7,
        'damaged': 0.5
    }
    
    # Adjustment by return reason
    if return_reason in ['defective', 'wrong_item']:
        # Full refund for seller/product issues
        multiplier = 1.0
        explanation = 'Full refund due to product issue'
    else:
        # Apply condition-based refund
        multiplier = condition_multipliers.get(condition, 0.7)
        explanation = f'{int(multiplier * 100)}% refund based on item condition: {condition}'
    
    refund_amount = round(original_price * multiplier, 2)
    
    return {
        'refund_amount': refund_amount,
        'refund_percentage': int(multiplier * 100),
        'explanation': explanation,
        'original_price': original_price
    }

@tool
def format_policy_response(policy_text: str, customer_question: str = '') -> str:
    """Format policy information in a customer-friendly way.
    
    Args:
        policy_text: Raw policy text from knowledge base
        customer_question: Optional customer question for context
    
    Returns:
        Formatted, customer-friendly policy explanation
    """
    # Clean up the text
    formatted = policy_text.strip()
    
    # Add friendly header if customer question provided
    if customer_question:
        response = f"Here's what I found about your question: '{customer_question}'\n\n"
    else:
        response = "Here's the relevant policy information:\n\n"
    
    # Add the policy text with better formatting
    response += formatted
    
    # Add helpful footer
    response += "\n\nIf you have any other questions about our return policy, feel free to ask!"
    
    return response


def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input"""
    
    # Build tools list
    custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
    
    # Create agent
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print("\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
