"""
AgentCore Runtime Agent: returns_agent_runtime
Generated by AgentCore MCP Server

This agent is ready to deploy to AgentCore Runtime with:
1. BedrockAgentCoreApp entrypoint
2. Memory integration
3. Gateway tools
4. Knowledge Base access
5. Custom tools for returns processing
"""

import os
import json
from bedrock_agentcore.runtime import BedrockAgentCoreApp
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from strands.tools.mcp import MCPClient
from mcp.client.streamable_http import streamablehttp_client
import requests
from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig
from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager
from datetime import datetime
import traceback

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Initialize app
app = BedrockAgentCoreApp()

# ============================================================================
# CUSTOM TOOL DEFINITIONS
# ============================================================================

@tool
def check_return_eligibility(purchase_date: str, category: str) -> dict:
    """Check if an item is eligible for return.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (e.g., 'electronics', 'clothing', 'books')
    
    Returns:
        dict with 'eligible' (bool) and 'reason' (str)
    """
    try:
        purchase = datetime.strptime(purchase_date, '%Y-%m-%d')
        today = datetime.now()
        days_since_purchase = (today - purchase).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 30,
            'books': 30,
            'jewelry': 30,
            'home': 30,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase <= window:
            return {
                'eligible': True,
                'reason': f'Item is within {window}-day return window ({days_since_purchase} days since purchase)'
            }
        else:
            return {
                'eligible': False,
                'reason': f'Item is outside {window}-day return window ({days_since_purchase} days since purchase)'
            }
    except ValueError:
        return {
            'eligible': False,
            'reason': 'Invalid date format. Please use YYYY-MM-DD format.'
        }
    except Exception as e:
        print(f"Error in check_return_eligibility: {e}")
        traceback.print_exc()
        return {
            'eligible': False,
            'reason': f'Error checking eligibility: {str(e)}'
        }

@tool
def calculate_refund_amount(original_price: float, condition: str, return_reason: str) -> dict:
    """Calculate the refund amount for a returned item.
    
    Args:
        original_price: Original purchase price
        condition: Item condition ('new', 'opened', 'used', 'damaged')
        return_reason: Reason for return ('defective', 'wrong_item', 'changed_mind', 'other')
    
    Returns:
        dict with 'refund_amount' (float), 'refund_percentage' (int), and 'explanation' (str)
    """
    try:
        condition = condition.lower()
        return_reason = return_reason.lower()
        
        # Base refund percentage by condition
        condition_multipliers = {
            'new': 1.0,
            'opened': 0.9,
            'used': 0.7,
            'damaged': 0.5
        }
        
        # Adjustment by return reason
        if return_reason in ['defective', 'wrong_item']:
            # Full refund for seller/product issues
            multiplier = 1.0
            explanation = 'Full refund due to product issue'
        else:
            # Apply condition-based refund
            multiplier = condition_multipliers.get(condition, 0.7)
            explanation = f'{int(multiplier * 100)}% refund based on item condition: {condition}'
        
        refund_amount = round(original_price * multiplier, 2)
        
        return {
            'refund_amount': refund_amount,
            'refund_percentage': int(multiplier * 100),
            'explanation': explanation,
            'original_price': original_price
        }
    except Exception as e:
        print(f"Error in calculate_refund_amount: {e}")
        traceback.print_exc()
        return {
            'refund_amount': 0.0,
            'refund_percentage': 0,
            'explanation': f'Error calculating refund: {str(e)}',
            'original_price': original_price
        }

@tool
def format_policy_response(policy_text: str, customer_question: str = '') -> str:
    """Format policy information in a customer-friendly way.
    
    Args:
        policy_text: Raw policy text from knowledge base
        customer_question: Optional customer question for context
    
    Returns:
        Formatted, customer-friendly policy explanation
    """
    try:
        # Clean up the text
        formatted = policy_text.strip()
        
        # Add friendly header if customer question provided
        if customer_question:
            response = f"Here's what I found about your question: '{customer_question}'\n\n"
        else:
            response = "Here's the relevant policy information:\n\n"
        
        # Add the policy text with better formatting
        response += formatted
        
        # Add helpful footer
        response += "\n\nIf you have any other questions about our return policy, feel free to ask!"
        
        return response
    except Exception as e:
        print(f"Error in format_policy_response: {e}")
        traceback.print_exc()
        return f"Error formatting policy response: {str(e)}"

# ============================================================================
# GATEWAY HELPER FUNCTIONS
# ============================================================================

def get_cognito_token_with_scope(client_id, client_secret, discovery_url, scope):
    """Get Cognito bearer token with a specific OAuth scope"""
    try:
        # Extract token endpoint from discovery URL
        discovery_response = requests.get(discovery_url, timeout=10)
        discovery_response.raise_for_status()
        token_endpoint = discovery_response.json()['token_endpoint']
        
        # Get token using client credentials flow
        response = requests.post(
            token_endpoint,
            data={
                'grant_type': 'client_credentials',
                'client_id': client_id,
                'client_secret': client_secret,
                'scope': scope
            },
            headers={'Content-Type': 'application/x-www-form-urlencoded'},
            timeout=10
        )
        
        response.raise_for_status()
        return response.json()["access_token"]
    except Exception as e:
        print(f"Error getting Cognito token: {e}")
        traceback.print_exc()
        raise

def create_mcp_client():
    """Create MCP client for gateway access"""
    try:
        # Get environment variables
        gateway_url = os.environ.get("GATEWAY_URL")
        cognito_client_id = os.environ.get("COGNITO_CLIENT_ID")
        cognito_client_secret = os.environ.get("COGNITO_CLIENT_SECRET")
        cognito_discovery_url = os.environ.get("COGNITO_DISCOVERY_URL")
        oauth_scopes = os.environ.get("OAUTH_SCOPES", "returns-gateway/read returns-gateway/write")
        
        if not all([gateway_url, cognito_client_id, cognito_client_secret, cognito_discovery_url]):
            print("Warning: Gateway environment variables not set - gateway tools will not be available")
            return None
        
        token = get_cognito_token_with_scope(
            cognito_client_id,
            cognito_client_secret,
            cognito_discovery_url,
            oauth_scopes
        )
        
        print(f"✓ Gateway configured: {gateway_url}")
        return MCPClient(
            lambda: streamablehttp_client(
                gateway_url,
                headers={"Authorization": f"Bearer {token}"},
            )
        )
    except Exception as e:
        print(f"Warning: Failed to create MCP client: {e}")
        traceback.print_exc()
        return None

# ============================================================================
# RUNTIME ENTRYPOINT
# ============================================================================

@app.entrypoint
def invoke(payload, context=None):
    """AgentCore Runtime entrypoint"""
    try:
        print("="*80)
        print("RUNTIME AGENT INVOCATION")
        print("="*80)
        
        # Initialize model inside the function (not at module level)
        bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)
        
        # Get environment variables
        memory_id = os.environ.get("MEMORY_ID")
        kb_id = os.environ.get("KNOWLEDGE_BASE_ID")
        
        if not memory_id:
            error_msg = "Error: MEMORY_ID environment variable is required"
            print(error_msg)
            return error_msg
        
        if not kb_id:
            error_msg = "Error: KNOWLEDGE_BASE_ID environment variable is required"
            print(error_msg)
            return error_msg
        
        print(f"✓ Memory ID: {memory_id}")
        print(f"✓ Knowledge Base ID: {kb_id}")
        
        # Get session and actor IDs
        session_id = context.session_id if context else SESSION_ID
        actor_id = payload.get("actor_id", ACTOR_ID)
        
        print(f"✓ Session ID: {session_id}")
        print(f"✓ Actor ID: {actor_id}")
        
        # System prompt with KB ID
        system_prompt = f"""Production returns assistant with full memory and gateway capabilities. Use the retrieve tool to access Amazon return policy documents for accurate information.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query

You have access to:
- Gateway tools for external operations (like order lookup)
- Customer conversation history and preferences through memory
- Custom tools for checking return eligibility and calculating refunds"""
        
        # Configure memory with retrieval settings
        try:
            agentcore_memory_config = AgentCoreMemoryConfig(
                memory_id=memory_id,
                session_id=session_id,
                actor_id=actor_id,
                retrieval_config={
                    f"app/{actor_id}/semantic": RetrievalConfig(top_k=3),
                    f"app/{actor_id}/preferences": RetrievalConfig(top_k=3),
                    f"app/{actor_id}/{session_id}/summary": RetrievalConfig(top_k=2),
                }
            )
            
            session_manager = AgentCoreMemorySessionManager(
                agentcore_memory_config=agentcore_memory_config,
                region_name=REGION
            )
            print("✓ Memory session manager configured")
        except Exception as e:
            error_msg = f"Error configuring memory: {e}"
            print(error_msg)
            traceback.print_exc()
            return error_msg
        
        # Custom tools list
        custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
        print(f"✓ Loaded {len(custom_tools)} custom tools")
        
        # Try to create MCP client for gateway tools
        mcp_client = create_mcp_client()
        
        if mcp_client:
            try:
                # Keep MCP client active during agent execution
                with mcp_client:
                    # Get gateway tools from MCP client
                    gateway_tools = list(mcp_client.list_tools_sync())
                    print(f"✓ Loaded {len(gateway_tools)} gateway tools")
                    
                    # Create agent with all tools
                    agent = Agent(
                        model=bedrock_model,
                        tools=custom_tools + gateway_tools,
                        system_prompt=system_prompt,
                        session_manager=session_manager
                    )
                    
                    user_input = payload.get("prompt", "")
                    print(f"\nUser Input: {user_input}")
                    print("="*80)
                    
                    response = agent(user_input)
                    result = response.message["content"][0]["text"]
                    
                    print("\n" + "="*80)
                    print("AGENT RESPONSE COMPLETE")
                    print("="*80)
                    
                    return result
            except Exception as e:
                print(f"Warning: Failed to use gateway tools: {e}")
                traceback.print_exc()
                # Fall back to agent without gateway tools
        
        # Create agent without gateway tools (fallback)
        print("⚠️  Running without gateway tools")
        agent = Agent(
            model=bedrock_model,
            tools=custom_tools,
            system_prompt=system_prompt,
            session_manager=session_manager
        )
        
        user_input = payload.get("prompt", "")
        print(f"\nUser Input: {user_input}")
        print("="*80)
        
        response = agent(user_input)
        result = response.message["content"][0]["text"]
        
        print("\n" + "="*80)
        print("AGENT RESPONSE COMPLETE")
        print("="*80)
        
        return result
    
    except Exception as e:
        error_msg = f"Agent invocation failed: {str(e)}"
        print(error_msg)
        traceback.print_exc()
        return error_msg

if __name__ == "__main__":
    app.run()
