#!/bin/bash

# Script to set up GitHub remote repository
# Run this after creating the repository on GitHub

echo "======================================================================"
echo "GitHub Repository Setup Instructions"
echo "======================================================================"
echo ""
echo "Step 1: Create the repository on GitHub"
echo "  - Go to: https://github.com/new"
echo "  - Repository name: bedrock-agentcore"
echo "  - Description: AWS Bedrock AgentCore Returns & Refunds Agent"
echo "  - Visibility: Choose Public or Private"
echo "  - DO NOT initialize with README, .gitignore, or license"
echo "  - Click 'Create repository'"
echo ""
echo "Step 2: Add the remote and push"
echo "  Run these commands:"
echo ""
echo "  git remote add origin https://github.com/k1ocke/bedrock-agentcore.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "======================================================================"
echo "Alternative: Use GitHub CLI (if installed)"
echo "======================================================================"
echo ""
echo "  gh repo create k1ocke/bedrock-agentcore --public --source=. --remote=origin"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "======================================================================"
echo "Current Status"
echo "======================================================================"
echo ""
echo "✓ Git repository initialized"
echo "✓ All files committed (40 files, 9534 insertions)"
echo "✓ .gitignore configured to exclude sensitive config files"
echo "✓ README.md created with project documentation"
echo ""
echo "Commit hash: $(git rev-parse HEAD)"
echo "Branch: $(git branch --show-current)"
echo ""
